### ISSUE TITLE
Release on crates.io

### ISSUE THREAD

**Issue by msdinit** [google-apis-rs/google-cloud-rs#25]
Hi!
I was wondering if you would consider releasing this crate `crates.io`.
I read from a previous issue that there are future plans to bundle this repo together with generated REST bindings and eventually release all of it, but I would like you to consider releasing a preview-like version of this crate in its current state as well.

My selfish reason for this request is extra-long download times for git submodule in my CI system, as well as build breaking with current nightly toolchain due to `rustfmt` not being available on it (which is required in the `build.rs` script)

**Comment by Hirevo** [comment]
Hi !
I was actually close to going forward with this, because, within my company, we have a project that we would wish to publish to a crate registry of our own and that project uses `google-cloud-rs` and Cargo denies publishing with a git dependency.  

So yeah, we could definitely publish this crate under `0.1.0`, keep bumping the minor version upon updates and keep it below `1.0.0` until maybe we have wide-enough coverage of all the GCP services.  
I'll start preparing a release with things like the README, the `Cargo.toml` attributes and maybe improving some doc comments.  

For the cloning speed, I've now opened #26 to track this issue, and its accompanying PR should follow pretty soon.  

Thanks for filing the issue !

**Comment by Hirevo** [comment]
[**`google-cloud 0.1.0`**](https://crates.io/crates/google-cloud) have now been released !! :tada:
