### ISSUE TITLE
Do you have plans to support KMS?

### ISSUE THREAD

**Issue by yagince** [google-apis-rs/google-cloud-rs#34]
I want to use kms, is there any plan to support kms in google-cloud-rs?

**Comment by Hirevo** [comment]
Hello !

Sorry for my long absence.  
Since KMS is a service from GCP, I am definitely not opposed to having it included, but I never used that service myself, therefore I am not very familiar with it and how it gets used in the wild.  
If you or anybody that is interested in it or using it can champion it and possibly provide an implementation, I'll definitely be welcoming it into the crate.

**Comment by yagince** [comment]
I see, I understand.
Thank you for your kind answer!

**Comment by GlenDC** [comment]
Can this be re-opened? I might want to help with supporting this. It would be my first contribution to the library however, so might need some guidance. Is the goal by the way to do this based on the generated code of the other repo of this project, or are the implementations mentioned here completely hand crafted?
